summary.TransModel <-
function(object,...){
  if(object$p==0){
    object$loglik<-loglik(object) 
    class(object)<-"summary.TransModel"
    return(object)
  }
   if(object$p>0){
	se<-sqrt(diag(object$vcov))
	zval<-coef(object)/se
	TAB<-cbind(Estimate=coef(object),
           StdErr=se,
           z.value=zval,
           p.value=2*pnorm(-abs(zval)))
      col<-ncol(object$data)-1
	rownames(TAB)<-names(object$coefficients)
	res<-list(call=object$call,p=object$p,loglik=loglik(object),AIC=-2*loglik(object)+2*object$p,
          coefficients=TAB)
	class(res)<-"summary.TransModel"
	return(res)
   }
}
